version: '3.3'

services:
  experiment:
    image: ciselab/codebert-code2text
    cpu_count: 8
    mem_limit: 32g
    oom_kill_disable: true
    oom_score_adj: 500
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
    environment:
      epochs: 5
      train_file: /dataset/train.jsonl
      valid_file: /dataset/valid.jsonl
      test_file: /dataset/test.jsonl
      batch_size: 8
      
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]