version: '3.3'

services:
  experiment:
    image: ciselab/codebert-code2text
    cpu_count: 8
    mem_limit: 32g
    oom_kill_disable: true
    oom_score_adj: 500
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
      - ./models/java:/models
    environment:
      do_train: "false"
      do_val: "true"
      do_test: "true"
      dev_file: /dataset/valid_minimal.jsonl
      test_file: /dataset/test_minimal.jsonl
      no_cuda: "true"
      #pretrained_model: microsoft/codebert-base
      pretrained_model: /models/pytorch_model.bin
