version: '3.8'

services:
  codebert_prediction_minimal_example:
    image: ciselab/codebert-code2text
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
      - ./compose_output/checkpoint-best-bleu:/models
    environment:
      DO_TRAIN: "false"
      DO_VALID: "true"
      DO_TEST: "true"
      valid_file: /dataset/valid_minimal.jsonl
      test_file: /dataset/test_minimal.jsonl
      no_cuda: "true"
      pretrained_model: microsoft/codebert-base
      load_existing_model: "true"
      load_model_path: /models/pytorch_model.bin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]