version: '3.8'

services:
  python-codebert-training:
    image: ciselab/codebert-code2text:1.3
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
    environment:
      epochs: 10
      lang: python
      train_file: /dataset/train.jsonl
      valid_file: /dataset/valid.jsonl
      test_file: /dataset/test.jsonl
      batch_size: 8
    oom_kill_disable: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]