version: '3.8'

services:
  codebert_python_training:
    image: ciselab/codebert-code2text:1.3
    volumes:
      - ./dataset/python/:/dataset:ro
      - ./python_compose_output:/experiment/output
    environment:
      epochs: 10
      lang: python
      train_file: /dataset/train.jsonl
      valid_file: /dataset/valid.jsonl
      test_file: /dataset/test.jsonl
      batch_size: 8
    oom_kill_disable: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]