version: '3.3'

services:
  experiment:
    image: experiment:unstable
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
    environment:
      epochs: 5
      train_file: /dataset/train.jsonl
      dev_file: /dataset/valid.jsonl
      test_file: /dataset/test.jsonl