version: '3.3'

services:
  experiment:
    image: ciselab/codebert-code2text
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
    environment:
      epochs: 10
      train_file: /dataset/train_minimal.jsonl
      valid_file: /dataset/valid_minimal.jsonl
      test_file: /dataset/test_minimal.jsonl
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]