version: '3.8'

services:
  experiment:
    image: ciselab/codebert-code2text
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
    environment:
      epochs: 10
      train_file: /dataset/train.jsonl
      valid_file: /dataset/valid.jsonl
      test_file: /dataset/test.jsonl
      batch_size: 8
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]