version: '3.8'

services:
  experiment:
    image: ciselab/codebert-code2text
    volumes:
      - ./dataset/java/:/dataset:ro
      - ./compose_output:/experiment/output
      - ./models/java:/models
    environment:
      do_train: "false"
      do_val: "true"
      do_test: "true"
      valid_file: /dataset/valid_minimal.jsonl
      test_file: /dataset/test_minimal.jsonl
      no_cuda: "true"
      pretrained_model: microsoft/codebert-base
      load_existing_model: "true"
      load_model_path: /models/best_pytorch_model.bin
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]